BracketSpace/Notification

inc/Settings.php
Add filter to allow devs to customize the arguments for what kinds of CPTs are populated in the settings.
=> Add filter for CPT arguments

class/Abstracts/Trigger.php, class/Defaults/Trigger/Post/PostPending.php, class/Defaults/Trigger/Post/PostPublished.php, class/Defaults/Trigger/Post/PostUpdated.php
=> ACF support

class/Admin/PostData.php, class/Admin/Settings.php, class/Defaults/Notification/Email.php, class/Utils/DocHooks.php, inc/defaults/notifications.php, readme.txt
@martinellimarco here's the new PR
=> Martinellimarco

class/Defaults/MergeTag/Avatar.php, class/Defaults/MergeTag/User/Avatar.php, class/Defaults/Trigger/Comment/CommentReplied.php, class/Defaults/Trigger/Comment/CommentTrigger.php, class/Defaults/Trigger/Media/MediaTrigger.php, class/Defaults/Trigger/Post/PostPublished.php, class/Defaults/Trigger/Post/PostTrashed.php, class/Defaults/Trigger/Post/PostTrigger.php, class/Defaults/Trigger/Post/PostUpdated.php, class/Defaults/Trigger/User/UserTrigger.php, inc/defaults/global-merge-tags.php, readme.txt
=> Add User Avatar MergeTag

class/Defaults/Recipient/UserID.php, inc/defaults/recipients.php, readme.txt
=> User ID recipient

class/Defaults/MergeTag/IntegerTag.php, class/Defaults/MergeTag/Post/FeaturedImageId.php, class/Defaults/Trigger/Post/PostTrigger.php, readme.txt
=> add featured image id merge tag

class/Abstracts/Field.php, class/Defaults/Carrier/Webhook.php, class/Defaults/Field/InputField.php, readme.txt
Adds this feature to the Webhook field as well
=> Allow Input field line breaks

class/Defaults/Carrier/Webhook.php, inc/defaults/recipients.php, readme.txt
=> add http_request method

class/Defaults/Trigger/Post/PostScheduled.php, readme.txt
=> Scheduling user merge tags for scheduled post trigger

.github/workflows/test.yml, src/assets/js/component/wizard.js, src/assets/scss/fields/_code-editor.scss, src/assets/scss/partials/_admin-wizard.scss, src/assets/scss/partials/_logs.scss
=> fix checkbox handler

readme.txt, src/classes/Defaults/Trigger/Post/PostApproved.php, src/classes/Defaults/Trigger/Post/PostPublished.php, src/includes/defaults/triggers.php
=> Post approved (#5cqbr2)

composer.lock, src/templates/debug/error-log.php, src/templates/debug/notification-log.php
=> Fix var tags

composer.json, composer.lock, readme.txt
@Kubitomakita Composer config was normalized by Composer's JSON schema.
=> Make PHP 7.0 the minimum supported version

.editorconfig
Helps user editing files here on GitHub.
The default is 8!
=> Set tab width in EditorConfig

src/assets/js/component/carriers-widget.js, src/assets/js/component/import-export.js, src/assets/js/component/logs.js, src/assets/js/component/mergetag.js, src/assets/js/component/pretty-select.js, src/assets/js/component/sync.js, src/assets/js/component/trigger.js, src/assets/js/component/wizard.js, src/assets/js/fields/image.js, src/assets/js/fields/repeater/components/inputs/select.js, src/assets/js/fields/repeater/mixins/fieldHandler.js, src/assets/js/fields/repeater/mixins/inputsHandler.js, src/assets/js/fields/section-repeater/components/select.js, src/assets/js/fields/section-repeater/mixins/inputNameHandler.js, src/assets/js/fields/section-repeater/mixins/sectionsHandler.js, src/assets/js/fields/section-repeater/mixins/sectionsModal.js
=> Fix JavaScript CS

readme.txt, src/classes/Defaults/Adapter/WordPress.php
=> Fix balance tags filter

.github/workflows/test.yml
=> Enable CI on PR-s

.github/workflows/test.yml
=> Run tests CI workflow on PR-s against release branches

phpstan-baseline.neon, readme.txt, src/Core/Processor.php, src/Core/Queue.php, src/Core/Runner.php, src/Integration/WordPress.php, src/Interfaces/Triggerable.php
resolve duplicate notification issue by proper queueing the notifications
=> Queue system for Background Processing

phpstan-baseline.neon, src/Defaults/Field/CodeEditorField.php
=> change code editor field sanitizer to none

src/Defaults/Field/EditorField.php
=> Simplify EditorField::sanitize

src/Utils/Settings.php, src/api.php
Allow updating single setting value based on standard `a/b/c` setting name format.
=> Allow updating single setting value

resources/js/src/fields/repeater/components/repeater/recipientRow.js, resources/js/src/fields/repeater/mixins/inputsHandler.js
=> Fix not working `disabled` attribute in carrier recipients

resources/wizard-data/comment_moderation.json, resources/wizard-data/comment_published.json, resources/wizard-data/comment_reply.json, resources/wizard-data/new_user.json, resources/wizard-data/password_forgotten.json, resources/wizard-data/password_reset.json, resources/wizard-data/post_published_admin.json, resources/wizard-data/post_published_subscribers.json, resources/wizard-data/post_review.json, resources/wizard-data/post_updated.json, resources/wizard-data/welcome_email.json, resources/wizard-data/your_account.json
My new tool: `git grep --perl-regexp --line-number -I '^(?!//)[^\t]+\t'`
[_source_](https://github.com/szepeviktor/byte-level-care/blob/4187017ab2fd44e5e335431d9c7084a5b2930ccd/.github/workflows/integrity.yml#L54-L57)
=> Remove midline tabs

src/Repository/Field/SectionRepeater.php
=> fix: fix section repeater table
